version: '3'

volumes:
  npm-home: ~

services:

  install-deps:
    image: node:alpine
    volumes:
      - $PWD:/app
      - npm-home:/tmp
    working_dir: /app
    user: $USER_ID
    command: npm install
    environment:
      - HOME=/tmp

  nginx:
    image: nginx:alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - $SERVER_PORT:80

  nodejs:
    image: node:alpine
    volumes:
      - $PWD:/app
    working_dir: /app
    environment:
      PORT: 3000
      HOST: 0.0.0.0
      MONGO_HOST: mongodb
    command: npm start

  mongodb:
    image: mongo
    restart: always
